spring.application.name=ecart-export

# MongoDB
app.mongodb.database=cart
app.item.collection=cart
app.category.collection=categories
app.control.collection=controlRef

# Server
server.port=8083

# App properties
app.error.categoryNotFound=Invalid Category ID
app.error.itemExists=Item already exists
app.records.processLimit=100

# Local folder paths
app.output.item-trend-analyzer=C:/Users/290561/eclipse-workspace/ecart-export/item-trend-analyzer
app.output.item-review-aggregator=C:/Users/290561/eclipse-workspace/ecart-export/item-review-aggregator
app.output.storefront-app=C:/Users/290561/eclipse-workspace/ecart-export/storefront-app

# Scheduler settings
# Run every 30 seconds
app.scheduler.cron=0/30 * * * * ?

camel.springboot.main-run-controller=true
logging.level.org.apache.camel=INFO
spring.main.allow-bean-definition-overriding=true

# MongoDB retry configuration
app.mongodb.retryAttempts=3
app.mongodb.initialDelay=60000
camel.component.mongodb.enabled=true
camel.component.mongodb.database=cart
camel.component.mongodb.host=localhost
camel.component.mongodb.port=27017   
